const loveNotes = [
  "Day 1 – I love the way your laugh feels like home, even on the worst days.",
  "Day 2 – Just thinking of you makes my chest feel lighter, like love itself is breathing for me.",
  "Day 3 – I adore how you know what I’m thinking before I say it… like our hearts share a language.",
  "Day 4 – I’m proud of the little things you do daily, the ones no one notices but me.",
  "Day 5 – Sometimes I catch myself smiling out of nowhere… and it’s always because of you.",
  "Day 6 – If love could be bottled, I’d keep yours on my nightstand so I never forget how lucky I am.",
  "Day 7 – I love your quirks, even the silly ones — especially the silly ones.",
  "Day 8 – You are my safe space, my chaos, my calm, and my favorite adventure all in one.",
  "Day 9 – I’d choose you in every lifetime, even if it meant finding you all over again.",
  "Day 10 – Ten days, ten notes, and still a lifetime to go. Each day with you feels like proof that forever is real.",
  "Day 11 – I love the way your voice softens when you’re sleepy. It’s the sweetest sound.",
  "Day 12 – You don’t just fill my heart, you expand it.",
  "Day 13 – I swear, even silence feels better when it’s with you.",
  "Day 14 – Love isn’t grand gestures with us, it’s in the tiny moments we collect quietly.",
  "Day 15 – You make me feel like I’m not just surviving life… I’m living it.",
  "Day 16 – Sometimes I get lost staring at you — not because I don’t know you, but because you feel infinite.",
  "Day 17 – You are my reason to believe in something bigger than myself.",
  "Day 18 – I love the way you hold me, like you’re afraid the world might steal me away.",
  "Day 19 – Your happiness is my favorite obsession.",
  "Day 20 – Being with you makes even ordinary days feel like milestones worth remembering.",
  "Day 21 – I adore the way time slows down when you’re near, and it makes me want a thousand more days with you.",
  "Day 22 – I love the way I feel safe when I’m with you, and that’s why I fall for you all over again.",
  "Day 23 – I can’t get over how the smallest glance from you makes my heart race, and it’s the sweetest gift I’ll ever have.",
  "Day 24 – It amazes me how your touch makes everything else disappear, and I wish I could freeze every moment with you.",
  "Day 25 – You’re the reason your touch makes everything else disappear, and I wish I could freeze every moment with you.",
  "Day 26 – You make me realize your smile brightens the dullest moments, and it’s the sweetest gift I’ll ever have.",
  "Day 27 – You’re the reason the smallest glance from you makes my heart race, and it makes me want a thousand more days with you.",
  "Day 28 – Every day I discover ordinary days become extraordinary with you, and that’s why I fall for you all over again.",
  "Day 29 – You make me realize I find home in your presence, and I’ll never stop being grateful for you.",
  "Day 30 – Every day I discover you make me believe in forever, and that’s my favorite part of life.",
  "Day 31 – I adore the way ordinary days become extraordinary with you, and that’s why forever feels too short with you.",
  "Day 32 – I adore the way your smile brightens the dullest moments, and I wish I could freeze every moment with you.",
  "Day 33 – It amazes me how the smallest glance from you makes my heart race, and that’s my favorite part of life.",
  "Day 34 – You make me realize ordinary days become extraordinary with you, and I’ll never stop being grateful for you.",
  "Day 35 – I adore the way your smile brightens the dullest moments, and I wouldn’t trade that for anything.",
  "Day 36 – It amazes me how you make me believe in forever, and I wish I could freeze every moment with you.",
  "Day 37 – Sometimes I think about your smile brightens the dullest moments, and I’d choose you in every universe.",
  "Day 38 – I adore the way time slows down when you’re near, and that’s why forever feels too short with you.",
  "Day 39 – I love the way I feel safe when I’m with you, and it reminds me how lucky I am to love you.",
  "Day 40 – Every day I discover you make me believe in forever, and I wish I could freeze every moment with you.",
  "Day 41 – It amazes me how you bring calm even to my storms, and that’s why I fall for you all over again.",
  "Day 42 – I adore the way you make me believe in forever, and that’s why I fall for you all over again.",
  "Day 43 – I adore the way time slows down when you’re near, and it makes me want a thousand more days with you.",
  "Day 44 – Sometimes I think about I feel safe when I’m with you, and that’s why I fall for you all over again.",
  "Day 45 – I love the way ordinary days become extraordinary with you, and it’s the sweetest gift I’ll ever have.",
  "Day 46 – I can’t get over how I feel safe when I’m with you, and I wish I could freeze every moment with you.",
  "Day 47 – I can’t get over how I feel safe when I’m with you, and I wouldn’t trade that for anything.",
  "Day 48 – You’re the reason time slows down when you’re near, and I’d choose you in every universe.",
  "Day 49 – Being with you feels like time slows down when you’re near, and it’s the sweetest gift I’ll ever have.",
  "Day 50 – Fifty days of love notes, yet my heart has written a thousand more for you.",
  "Day 51 – I love the way your touch makes everything else disappear, and I wish I could freeze every moment with you.",
  "Day 52 – I adore the way ordinary days become extraordinary with you, and I’d choose you in every universe.",
  "Day 53 – You’re the reason I feel safe when I’m with you, and it reminds me how lucky I am to love you.",
  "Day 54 – Every day I discover your laughter feels like a song written just for me, and I’d choose you in every universe.",
  "Day 55 – Being with you feels like time slows down when you’re near, and I’d choose you in every universe.",
  "Day 56 – I love the way you make me believe in forever, and that’s my favorite part of life.",
  "Day 57 – You’re the reason you bring calm even to my storms, and it reminds me how lucky I am to love you.",
  "Day 58 – I adore the way you bring calm even to my storms, and I wish I could freeze every moment with you.",
  "Day 59 – You make me realize I feel safe when I’m with you, and it’s the sweetest gift I’ll ever have.",
  "Day 60 – Being with you feels like your smile brightens the dullest moments, and I’d choose you in every universe.",
  "Day 61 – You make me realize you bring calm even to my storms, and I’d choose you in every universe.",
  "Day 62 – It amazes me how your laughter feels like a song written just for me, and I’ll never stop being grateful for you.",
  "Day 63 – I love the way you bring calm even to my storms, and I’d choose you in every universe.",
  "Day 64 – You make me realize your smile brightens the dullest moments, and that’s why forever feels too short with you.",
  "Day 65 – It amazes me how I find home in your presence, and it’s the sweetest gift I’ll ever have.",
  "Day 66 – Sometimes I think about your laughter feels like a song written just for me, and that’s why forever feels too short with you.",
  "Day 67 – I adore the way ordinary days become extraordinary with you, and it makes me want a thousand more days with you.",
  "Day 68 – Being with you feels like I feel safe when I’m with you, and it makes me want a thousand more days with you.",
  "Day 69 – Being with you feels like you bring calm even to my storms, and it’s the sweetest gift I’ll ever have.",
  "Day 70 – Sometimes I think about I find home in your presence, and it makes me want a thousand more days with you.",
  "Day 71 – There’s magic in the way the smallest glance from you makes my heart race, and that’s why forever feels too short with you.",
  "Day 72 – You make me realize I find home in your presence, and it reminds me how lucky I am to love you.",
  "Day 73 – It amazes me how I find home in your presence, and that’s my favorite part of life.",
  "Day 74 – Being with you feels like you make me believe in forever, and that’s my favorite part of life.",
  "Day 75 – There’s magic in the way I feel safe when I’m with you, and that’s why forever feels too short with you.",
  "Day 76 – There’s magic in the way I feel safe when I’m with you, and that’s my favorite part of life.",
  "Day 77 – I love the way ordinary days become extraordinary with you, and I’d choose you in every universe.",
  "Day 78 – I can’t get over how time slows down when you’re near, and it makes me want a thousand more days with you.",
  "Day 79 – You make me realize I feel safe when I’m with you, and that’s why I fall for you all over again.",
  "Day 80 – I adore the way your smile brightens the dullest moments, and that’s my favorite part of life.",
  "Day 81 – There’s magic in the way your touch makes everything else disappear, and I wouldn’t trade that for anything.",
  "Day 82 – There’s magic in the way the smallest glance from you makes my heart race, and it reminds me how lucky I am to love you.",
  "Day 83 – It amazes me how I find home in your presence, and it reminds me how lucky I am to love you.",
  "Day 84 – You make me realize your smile brightens the dullest moments, and I’d choose you in every universe.",
  "Day 85 – There’s magic in the way I feel safe when I’m with you, and that’s my favorite part of life.",
  "Day 86 – It amazes me how your laughter feels like a song written just for me, and I wouldn’t trade that for anything.",
  "Day 87 – I adore the way time slows down when you’re near, and it reminds me how lucky I am to love you.",
  "Day 88 – Every day I discover ordinary days become extraordinary with you, and I’d choose you in every universe.",
  "Day 89 – You make me realize your laughter feels like a song written just for me, and it makes me want a thousand more days with you.",
  "Day 90 – I love the way you bring calm even to my storms, and that’s my favorite part of life.",
  "Day 91 – You make me realize your touch makes everything else disappear, and I wouldn’t trade that for anything.",
  "Day 92 – Being with you feels like your smile brightens the dullest moments, and it reminds me how lucky I am to love you.",
  "Day 93 – I can’t get over how I feel safe when I’m with you, and that’s why forever feels too short with you.",
  "Day 94 – I can’t get over how you bring calm even to my storms, and that’s my favorite part of life.",
  "Day 95 – Being with you feels like you make me believe in forever, and that’s my favorite part of life.",
  "Day 96 – Sometimes I think about the smallest glance from you makes my heart race, and I’d choose you in every universe.",
  "Day 97 – I adore the way your touch makes everything else disappear, and I’d choose you in every universe.",
  "Day 98 – Every day I discover you bring calm even to my storms, and I’ll never stop being grateful for you.",
  "Day 99 – Being with you feels like you make me believe in forever, and that’s my favorite part of life.",
  "Day 100 – One hundred days, and it still feels like we’re at the beginning of forever.",
  "Day 101 – It amazes me how I find home in your presence, and it makes me want a thousand more days with you.",
  "Day 102 – Being with you feels like your smile brightens the dullest moments, and I wouldn’t trade that for anything.",
  "Day 103 – It amazes me how the smallest glance from you makes my heart race, and I’d choose you in every universe.",
  "Day 104 – It amazes me how your smile brightens the dullest moments, and that’s my favorite part of life.",
  "Day 105 – You’re the reason ordinary days become extraordinary with you, and I wish I could freeze every moment with you.",
  "Day 106 – I adore the way you bring calm even to my storms, and that’s my favorite part of life.",
  "Day 107 – I adore the way your laughter feels like a song written just for me, and I wouldn’t trade that for anything.",
  "Day 108 – There’s magic in the way your touch makes everything else disappear, and I wish I could freeze every moment with you.",
  "Day 109 – There’s magic in the way your touch makes everything else disappear, and I’ll never stop being grateful for you.",
  "Day 110 – I love the way your touch makes everything else disappear, and that’s why forever feels too short with you.",
  "Day 111 – There’s magic in the way your touch makes everything else disappear, and that’s why I fall for you all over again.",
  "Day 112 – Sometimes I think about your smile brightens the dullest moments, and it makes me want a thousand more days with you.",
  "Day 113 – Sometimes I think about I feel safe when I’m with you, and that’s why I fall for you all over again.",
  "Day 114 – There’s magic in the way the smallest glance from you makes my heart race, and it’s the sweetest gift I’ll ever have.",
  "Day 115 – It amazes me how you bring calm even to my storms, and it makes me want a thousand more days with you.",
  "Day 116 – You’re the reason ordinary days become extraordinary with you, and I wish I could freeze every moment with you.",
  "Day 117 – It amazes me how I feel safe when I’m with you, and I wish I could freeze every moment with you.",
  "Day 118 – I love the way you make me believe in forever, and it reminds me how lucky I am to love you.",
  "Day 119 – Sometimes I think about I find home in your presence, and I wouldn’t trade that for anything.",
  "Day 120 – I adore the way time slows down when you’re near, and I wish I could freeze every moment with you.",
  "Day 121 – I love the way you bring calm even to my storms, and I’ll never stop being grateful for you.",
  "Day 122 – Being with you feels like ordinary days become extraordinary with you, and it makes me want a thousand more days with you.",
  "Day 123 – I can’t get over how your smile brightens the dullest moments, and it’s the sweetest gift I’ll ever have.",
  "Day 124 – You’re the reason ordinary days become extraordinary with you, and I wish I could freeze every moment with you.",
  "Day 125 – Sometimes I think about I feel safe when I’m with you, and I’ll never stop being grateful for you.",
  "Day 126 – Every day I discover you make me believe in forever, and it reminds me how lucky I am to love you.",
  "Day 127 – Every day I discover ordinary days become extraordinary with you, and I’ll never stop being grateful for you.",
  "Day 128 – You’re the reason you bring calm even to my storms, and it reminds me how lucky I am to love you.",
  "Day 129 – You make me realize your laughter feels like a song written just for me, and I’ll never stop being grateful for you.",
  "Day 130 – You make me realize your laughter feels like a song written just for me, and I wouldn’t trade that for anything.",
  "Day 131 – I love the way time slows down when you’re near, and I’d choose you in every universe.",
  "Day 132 – There’s magic in the way I feel safe when I’m with you, and it reminds me how lucky I am to love you.",
  "Day 133 – It amazes me how ordinary days become extraordinary with you, and I wish I could freeze every moment with you.",
  "Day 134 – You’re the reason you bring calm even to my storms, and that’s why I fall for you all over again.",
  "Day 135 – You make me realize you bring calm even to my storms, and I wouldn’t trade that for anything.",
  "Day 136 – I adore the way you bring calm even to my storms, and that’s why forever feels too short with you.",
  "Day 137 – Being with you feels like you make me believe in forever, and that’s why forever feels too short with you.",
  "Day 138 – You’re the reason your laughter feels like a song written just for me, and I’d choose you in every universe.",
  "Day 139 – Every day I discover you make me believe in forever, and it makes me want a thousand more days with you.",
  "Day 140 – I can’t get over how your smile brightens the dullest moments, and I wouldn’t trade that for anything.",
  "Day 141 – It amazes me how time slows down when you’re near, and I’ll never stop being grateful for you.",
  "Day 142 – There’s magic in the way you bring calm even to my storms, and it’s the sweetest gift I’ll ever have.",
  "Day 143 – I can’t get over how ordinary days become extraordinary with you, and that’s why forever feels too short with you.",
  "Day 144 – There’s magic in the way the smallest glance from you makes my heart race, and it makes me want a thousand more days with you.",
  "Day 145 – It amazes me how I feel safe when I’m with you, and I wish I could freeze every moment with you.",
  "Day 146 – Being with you feels like your touch makes everything else disappear, and that’s why I fall for you all over again.",
  "Day 147 – I can’t get over how I find home in your presence, and I wish I could freeze every moment with you.",
  "Day 148 – Sometimes I think about your laughter feels like a song written just for me, and that’s why I fall for you all over again.",
  "Day 149 – It amazes me how you make me believe in forever, and it’s the sweetest gift I’ll ever have.",
  "Day 150 – I love the way the smallest glance from you makes my heart race, and I wouldn’t trade that for anything.",
  "Day 151 – Being with you feels like your smile brightens the dullest moments, and I wish I could freeze every moment with you.",
  "Day 152 – It amazes me how time slows down when you’re near, and I’d choose you in every universe.",
  "Day 153 – Being with you feels like your touch makes everything else disappear, and I’d choose you in every universe.",
  "Day 154 – Sometimes I think about I find home in your presence, and that’s my favorite part of life.",
  "Day 155 – Sometimes I think about you make me believe in forever, and I wouldn’t trade that for anything.",
  "Day 156 – You’re the reason your touch makes everything else disappear, and it reminds me how lucky I am to love you.",
  "Day 157 – There’s magic in the way I find home in your presence, and that’s why forever feels too short with you.",
  "Day 158 – You make me realize time slows down when you’re near, and it makes me want a thousand more days with you.",
  "Day 159 – There’s magic in the way I feel safe when I’m with you, and it’s the sweetest gift I’ll ever have.",
  "Day 160 – You’re the reason I find home in your presence, and I wouldn’t trade that for anything.",
  "Day 161 – Being with you feels like your laughter feels like a song written just for me, and it reminds me how lucky I am to love you.",
  "Day 162 – Every day I discover your smile brightens the dullest moments, and I wish I could freeze every moment with you.",
  "Day 163 – I love the way the smallest glance from you makes my heart race, and I’ll never stop being grateful for you.",
  "Day 164 – Being with you feels like you make me believe in forever, and it’s the sweetest gift I’ll ever have.",
  "Day 165 – Being with you feels like time slows down when you’re near, and it makes me want a thousand more days with you.",
  "Day 166 – It amazes me how your touch makes everything else disappear, and that’s why forever feels too short with you.",
  "Day 167 – Being with you feels like I find home in your presence, and it makes me want a thousand more days with you.",
  "Day 168 – Sometimes I think about you bring calm even to my storms, and it reminds me how lucky I am to love you.",
  "Day 169 – You make me realize you bring calm even to my storms, and it makes me want a thousand more days with you.",
  "Day 170 – You’re the reason your smile brightens the dullest moments, and that’s my favorite part of life.",
  "Day 171 – I can’t get over how the smallest glance from you makes my heart race, and that’s my favorite part of life.",
  "Day 172 – I love the way your smile brightens the dullest moments, and it reminds me how lucky I am to love you.",
  "Day 173 – Being with you feels like your touch makes everything else disappear, and it makes me want a thousand more days with you.",
  "Day 174 – Being with you feels like I feel safe when I’m with you, and it reminds me how lucky I am to love you.",
  "Day 175 – I adore the way your touch makes everything else disappear, and that’s why I fall for you all over again.",
  "Day 176 – Being with you feels like the smallest glance from you makes my heart race, and I’d choose you in every universe.",
  "Day 177 – You’re the reason the smallest glance from you makes my heart race, and I’d choose you in every universe.",
  "Day 178 – I love the way the smallest glance from you makes my heart race, and it’s the sweetest gift I’ll ever have.",
  "Day 179 – It amazes me how you make me believe in forever, and I’d choose you in every universe.",
  "Day 180 – You make me realize your laughter feels like a song written just for me, and that’s why I fall for you all over again.",
  "Day 181 – You make me realize you bring calm even to my storms, and that’s my favorite part of life.",
  "Day 182 – You make me realize the smallest glance from you makes my heart race, and it makes me want a thousand more days with you.",
  "Day 183 – It amazes me how the smallest glance from you makes my heart race, and I’ll never stop being grateful for you.",
  "Day 184 – Every day I discover ordinary days become extraordinary with you, and it reminds me how lucky I am to love you.",
  "Day 185 – You’re the reason you bring calm even to my storms, and I’d choose you in every universe.",
  "Day 186 – Being with you feels like the smallest glance from you makes my heart race, and that’s my favorite part of life.",
  "Day 187 – Every day I discover ordinary days become extraordinary with you, and I’d choose you in every universe.",
  "Day 188 – Being with you feels like you make me believe in forever, and that’s why I fall for you all over again.",
  "Day 189 – I adore the way the smallest glance from you makes my heart race, and I’d choose you in every universe.",
  "Day 190 – Being with you feels like I find home in your presence, and I’d choose you in every universe.",
  "Day 191 – It amazes me how you bring calm even to my storms, and it makes me want a thousand more days with you.",
  "Day 192 – I adore the way time slows down when you’re near, and it makes me want a thousand more days with you.",
  "Day 193 – I can’t get over how your smile brightens the dullest moments, and I wish I could freeze every moment with you.",
  "Day 194 – It amazes me how I feel safe when I’m with you, and I wouldn’t trade that for anything.",
  "Day 195 – You make me realize time slows down when you’re near, and I’ll never stop being grateful for you.",
  "Day 196 – Being with you feels like your touch makes everything else disappear, and I’d choose you in every universe.",
  "Day 197 – Being with you feels like I find home in your presence, and I’ll never stop being grateful for you.",
  "Day 198 – Sometimes I think about your touch makes everything else disappear, and I wouldn’t trade that for anything.",
  "Day 199 – Being with you feels like I find home in your presence, and that’s why I fall for you all over again.",
  "Day 200 – Two hundred days of words, yet I’ve barely scratched the surface of how much I love you.",
  "Day 201 – I adore the way I feel safe when I’m with you, and I wish I could freeze every moment with you.",
  "Day 202 – I can’t get over how you make me believe in forever, and it’s the sweetest gift I’ll ever have.",
  "Day 203 – It amazes me how your touch makes everything else disappear, and I’d choose you in every universe.",
  "Day 204 – Sometimes I think about time slows down when you’re near, and I wish I could freeze every moment with you.",
  "Day 205 – Sometimes I think about ordinary days become extraordinary with you, and it reminds me how lucky I am to love you.",
  "Day 206 – There’s magic in the way I feel safe when I’m with you, and it’s the sweetest gift I’ll ever have.",
  "Day 207 – Being with you feels like your smile brightens the dullest moments, and it makes me want a thousand more days with you.",
  "Day 208 – Being with you feels like I feel safe when I’m with you, and that’s my favorite part of life.",
  "Day 209 – It amazes me how the smallest glance from you makes my heart race, and it makes me want a thousand more days with you.",
  "Day 210 – It amazes me how you make me believe in forever, and it reminds me how lucky I am to love you.",
  "Day 211 – You’re the reason time slows down when you’re near, and that’s my favorite part of life.",
  "Day 212 – You make me realize ordinary days become extraordinary with you, and it’s the sweetest gift I’ll ever have.",
  "Day 213 – I love the way I find home in your presence, and I wish I could freeze every moment with you.",
  "Day 214 – I can’t get over how you bring calm even to my storms, and I wouldn’t trade that for anything.",
  "Day 215 – Sometimes I think about I feel safe when I’m with you, and I wouldn’t trade that for anything.",
  "Day 216 – There’s magic in the way you bring calm even to my storms, and that’s my favorite part of life.",
  "Day 217 – It amazes me how your touch makes everything else disappear, and that’s why I fall for you all over again.",
  "Day 218 – You’re the reason your touch makes everything else disappear, and I wish I could freeze every moment with you.",
  "Day 219 – I love the way time slows down when you’re near, and it makes me want a thousand more days with you.",
  "Day 220 – Every day I discover time slows down when you’re near, and that’s my favorite part of life.",
  "Day 221 – You’re the reason your touch makes everything else disappear, and I’ll never stop being grateful for you.",
  "Day 222 – I love the way ordinary days become extraordinary with you, and it makes me want a thousand more days with you.",
  "Day 223 – I adore the way you bring calm even to my storms, and I wouldn’t trade that for anything.",
  "Day 224 – Sometimes I think about your touch makes everything else disappear, and it makes me want a thousand more days with you.",
  "Day 225 – There’s magic in the way the smallest glance from you makes my heart race, and it’s the sweetest gift I’ll ever have.",
  "Day 226 – You’re the reason you make me believe in forever, and that’s why forever feels too short with you.",
  "Day 227 – Every day I discover your laughter feels like a song written just for me, and that’s my favorite part of life.",
  "Day 228 – There’s magic in the way the smallest glance from you makes my heart race, and it’s the sweetest gift I’ll ever have.",
  "Day 229 – I love the way you make me believe in forever, and I wish I could freeze every moment with you.",
  "Day 230 – Sometimes I think about I find home in your presence, and it’s the sweetest gift I’ll ever have.",
  "Day 231 – It amazes me how your touch makes everything else disappear, and it reminds me how lucky I am to love you.",
  "Day 232 – Sometimes I think about your touch makes everything else disappear, and I’d choose you in every universe.",
  "Day 233 – Being with you feels like you bring calm even to my storms, and it makes me want a thousand more days with you.",
  "Day 234 – Every day I discover your laughter feels like a song written just for me, and that’s my favorite part of life.",
  "Day 235 – You make me realize you bring calm even to my storms, and it reminds me how lucky I am to love you.",
  "Day 236 – I love the way time slows down when you’re near, and it’s the sweetest gift I’ll ever have.",
  "Day 237 – Every day I discover you bring calm even to my storms, and I wish I could freeze every moment with you.",
  "Day 238 – I can’t get over how the smallest glance from you makes my heart race, and I wish I could freeze every moment with you.",
  "Day 239 – Being with you feels like you make me believe in forever, and it reminds me how lucky I am to love you.",
  "Day 240 – Sometimes I think about you make me believe in forever, and that’s why I fall for you all over again.",
  "Day 241 – You make me realize time slows down when you’re near, and that’s my favorite part of life.",
  "Day 242 – I can’t get over how you make me believe in forever, and that’s why forever feels too short with you.",
  "Day 243 – I adore the way your laughter feels like a song written just for me, and that’s why I fall for you all over again.",
  "Day 244 – You’re the reason you make me believe in forever, and that’s my favorite part of life.",
  "Day 245 – I adore the way I find home in your presence, and I’ll never stop being grateful for you.",
  "Day 246 – There’s magic in the way time slows down when you’re near, and I’d choose you in every universe.",
  "Day 247 – You’re the reason I feel safe when I’m with you, and I wish I could freeze every moment with you.",
  "Day 248 – I can’t get over how I feel safe when I’m with you, and I wish I could freeze every moment with you.",
  "Day 249 – Sometimes I think about you make me believe in forever, and that’s my favorite part of life.",
  "Day 250 – There’s magic in the way your laughter feels like a song written just for me, and it reminds me how lucky I am to love you.",
  "Day 251 – It amazes me how you bring calm even to my storms, and I wish I could freeze every moment with you.",
  "Day 252 – I can’t get over how I feel safe when I’m with you, and it makes me want a thousand more days with you.",
  "Day 253 – There’s magic in the way you bring calm even to my storms, and I’d choose you in every universe.",
  "Day 254 – You make me realize I find home in your presence, and I wouldn’t trade that for anything.",
  "Day 255 – I adore the way I feel safe when I’m with you, and that’s why forever feels too short with you.",
  "Day 256 – I love the way your laughter feels like a song written just for me, and I wish I could freeze every moment with you.",
  "Day 257 – I adore the way you bring calm even to my storms, and it makes me want a thousand more days with you.",
  "Day 258 – There’s magic in the way your laughter feels like a song written just for me, and that’s why I fall for you all over again.",
  "Day 259 – Being with you feels like you bring calm even to my storms, and that’s my favorite part of life.",
  "Day 260 – Being with you feels like your laughter feels like a song written just for me, and it’s the sweetest gift I’ll ever have.",
  "Day 261 – Being with you feels like I feel safe when I’m with you, and that’s my favorite part of life.",
  "Day 262 – I adore the way you make me believe in forever, and I wish I could freeze every moment with you.",
  "Day 263 – Being with you feels like time slows down when you’re near, and I’ll never stop being grateful for you.",
  "Day 264 – There’s magic in the way your smile brightens the dullest moments, and it makes me want a thousand more days with you.",
  "Day 265 – Every day I discover you make me believe in forever, and I’d choose you in every universe.",
  "Day 266 – There’s magic in the way you make me believe in forever, and it’s the sweetest gift I’ll ever have.",
  "Day 267 – There’s magic in the way you bring calm even to my storms, and it makes me want a thousand more days with you.",
  "Day 268 – I adore the way ordinary days become extraordinary with you, and that’s why I fall for you all over again.",
  "Day 269 – Sometimes I think about your touch makes everything else disappear, and I wish I could freeze every moment with you.",
  "Day 270 – It amazes me how your touch makes everything else disappear, and it makes me want a thousand more days with you.",
  "Day 271 – Being with you feels like time slows down when you’re near, and that’s my favorite part of life.",
  "Day 272 – You’re the reason time slows down when you’re near, and it’s the sweetest gift I’ll ever have.",
  "Day 273 – There’s magic in the way your touch makes everything else disappear, and it reminds me how lucky I am to love you.",
  "Day 274 – I adore the way I feel safe when I’m with you, and I wouldn’t trade that for anything.",
  "Day 275 – Every day I discover I find home in your presence, and it reminds me how lucky I am to love you.",
  "Day 276 – You make me realize you bring calm even to my storms, and it reminds me how lucky I am to love you.",
  "Day 277 – Being with you feels like the smallest glance from you makes my heart race, and that’s my favorite part of life.",
  "Day 278 – Every day I discover ordinary days become extraordinary with you, and it reminds me how lucky I am to love you.",
  "Day 279 – I adore the way I find home in your presence, and it reminds me how lucky I am to love you.",
  "Day 280 – You’re the reason your laughter feels like a song written just for me, and I’ll never stop being grateful for you.",
  "Day 281 – You’re the reason your laughter feels like a song written just for me, and I wish I could freeze every moment with you.",
  "Day 282 – Every day I discover ordinary days become extraordinary with you, and it’s the sweetest gift I’ll ever have.",
  "Day 283 – I can’t get over how you bring calm even to my storms, and it reminds me how lucky I am to love you.",
  "Day 284 – Every day I discover I find home in your presence, and it’s the sweetest gift I’ll ever have.",
  "Day 285 – You make me realize the smallest glance from you makes my heart race, and it’s the sweetest gift I’ll ever have.",
  "Day 286 – You’re the reason your laughter feels like a song written just for me, and that’s why forever feels too short with you.",
  "Day 287 – There’s magic in the way the smallest glance from you makes my heart race, and I wish I could freeze every moment with you.",
  "Day 288 – I love the way you make me believe in forever, and it makes me want a thousand more days with you.",
  "Day 289 – There’s magic in the way the smallest glance from you makes my heart race, and it reminds me how lucky I am to love you.",
  "Day 290 – Every day I discover time slows down when you’re near, and it reminds me how lucky I am to love you.",
  "Day 291 – I adore the way your touch makes everything else disappear, and that’s why I fall for you all over again.",
  "Day 292 – You’re the reason your laughter feels like a song written just for me, and I’d choose you in every universe.",
  "Day 293 – Being with you feels like you make me believe in forever, and that’s why forever feels too short with you.",
  "Day 294 – Being with you feels like you make me believe in forever, and I wish I could freeze every moment with you.",
  "Day 295 – You’re the reason your smile brightens the dullest moments, and I wouldn’t trade that for anything.",
  "Day 296 – It amazes me how you make me believe in forever, and that’s why forever feels too short with you.",
  "Day 297 – Sometimes I think about your smile brightens the dullest moments, and it makes me want a thousand more days with you.",
  "Day 298 – I can’t get over how your laughter feels like a song written just for me, and I’d choose you in every universe.",
  "Day 299 – You’re the reason you make me believe in forever, and I wish I could freeze every moment with you.",
  "Day 300 – It amazes me how the smallest glance from you makes my heart race, and I wouldn’t trade that for anything.",
  "Day 301 – There’s magic in the way your laughter feels like a song written just for me, and that’s my favorite part of life.",
  "Day 302 – Sometimes I think about your laughter feels like a song written just for me, and I wish I could freeze every moment with you.",
  "Day 303 – I love the way ordinary days become extraordinary with you, and it reminds me how lucky I am to love you.",
  "Day 304 – I love the way you bring calm even to my storms, and that’s why I fall for you all over again.",
  "Day 305 – I adore the way I feel safe when I’m with you, and that’s why I fall for you all over again.",
  "Day 306 – You’re the reason I find home in your presence, and I wish I could freeze every moment with you.",
  "Day 307 – Every day I discover your touch makes everything else disappear, and that’s why I fall for you all over again.",
  "Day 308 – I adore the way the smallest glance from you makes my heart race, and I’d choose you in every universe.",
  "Day 309 – I love the way ordinary days become extraordinary with you, and it’s the sweetest gift I’ll ever have.",
  "Day 310 – I love the way ordinary days become extraordinary with you, and it makes me want a thousand more days with you.",
  "Day 311 – You’re the reason time slows down when you’re near, and I wouldn’t trade that for anything.",
  "Day 312 – You’re the reason you make me believe in forever, and it reminds me how lucky I am to love you.",
  "Day 313 – I love the way your smile brightens the dullest moments, and that’s why I fall for you all over again.",
  "Day 314 – There’s magic in the way your smile brightens the dullest moments, and that’s my favorite part of life.",
  "Day 315 – I love the way the smallest glance from you makes my heart race, and it reminds me how lucky I am to love you.",
  "Day 316 – You’re the reason you make me believe in forever, and it’s the sweetest gift I’ll ever have.",
  "Day 317 – You make me realize I feel safe when I’m with you, and I’d choose you in every universe.",
  "Day 318 – I adore the way you make me believe in forever, and I’d choose you in every universe.",
  "Day 319 – You’re the reason ordinary days become extraordinary with you, and that’s why forever feels too short with you.",
  "Day 320 – You’re the reason you make me believe in forever, and I’d choose you in every universe.",
  "Day 321 – There’s magic in the way your laughter feels like a song written just for me, and it makes me want a thousand more days with you.",
  "Day 322 – You’re the reason the smallest glance from you makes my heart race, and it reminds me how lucky I am to love you.",
  "Day 323 – I adore the way I feel safe when I’m with you, and it makes me want a thousand more days with you.",
  "Day 324 – Every day I discover your smile brightens the dullest moments, and I wouldn’t trade that for anything.",
  "Day 325 – You’re the reason ordinary days become extraordinary with you, and I wish I could freeze every moment with you.",
  "Day 326 – I adore the way your laughter feels like a song written just for me, and I wouldn’t trade that for anything.",
  "Day 327 – Sometimes I think about time slows down when you’re near, and that’s why I fall for you all over again.",
  "Day 328 – I can’t get over how ordinary days become extraordinary with you, and I’d choose you in every universe.",
  "Day 329 – It amazes me how ordinary days become extraordinary with you, and it’s the sweetest gift I’ll ever have.",
  "Day 330 – Every day I discover time slows down when you’re near, and that’s why I fall for you all over again.",
  "Day 331 – You’re the reason I find home in your presence, and I wish I could freeze every moment with you.",
  "Day 332 – There’s magic in the way your laughter feels like a song written just for me, and I wouldn’t trade that for anything.",
  "Day 333 – You make me realize you make me believe in forever, and I wish I could freeze every moment with you.",
  "Day 334 – You make me realize your touch makes everything else disappear, and that’s why forever feels too short with you.",
  "Day 335 – There’s magic in the way your touch makes everything else disappear, and it makes me want a thousand more days with you.",
  "Day 336 – There’s magic in the way I find home in your presence, and that’s why I fall for you all over again.",
  "Day 337 – I can’t get over how your laughter feels like a song written just for me, and it reminds me how lucky I am to love you.",
  "Day 338 – Every day I discover your touch makes everything else disappear, and I wouldn’t trade that for anything.",
  "Day 339 – Being with you feels like the smallest glance from you makes my heart race, and that’s why forever feels too short with you.",
  "Day 340 – Sometimes I think about ordinary days become extraordinary with you, and it’s the sweetest gift I’ll ever have.",
  "Day 341 – There’s magic in the way I feel safe when I’m with you, and it reminds me how lucky I am to love you.",
  "Day 342 – I love the way your touch makes everything else disappear, and it’s the sweetest gift I’ll ever have.",
  "Day 343 – I adore the way the smallest glance from you makes my heart race, and it reminds me how lucky I am to love you.",
  "Day 344 – Being with you feels like ordinary days become extraordinary with you, and that’s why I fall for you all over again.",
  "Day 345 – It amazes me how I find home in your presence, and that’s my favorite part of life.",
  "Day 346 – Sometimes I think about the smallest glance from you makes my heart race, and that’s my favorite part of life.",
  "Day 347 – It amazes me how you make me believe in forever, and that’s why forever feels too short with you.",
  "Day 348 – It amazes me how I find home in your presence, and it reminds me how lucky I am to love you.",
  "Day 349 – You make me realize time slows down when you’re near, and it makes me want a thousand more days with you.",
  "Day 350 – You’re the reason I find home in your presence, and it’s the sweetest gift I’ll ever have.",
  "Day 351 – Sometimes I think about the smallest glance from you makes my heart race, and I’d choose you in every universe.",
  "Day 352 – I love the way ordinary days become extraordinary with you, and I wouldn’t trade that for anything.",
  "Day 353 – You’re the reason ordinary days become extraordinary with you, and it makes me want a thousand more days with you.",
  "Day 354 – You’re the reason you make me believe in forever, and that’s why I fall for you all over again.",
  "Day 355 – You’re the reason ordinary days become extraordinary with you, and I wouldn’t trade that for anything.",
  "Day 356 – You’re the reason I find home in your presence, and that’s why I fall for you all over again.",
  "Day 357 – You make me realize you make me believe in forever, and it reminds me how lucky I am to love you.",
  "Day 358 – You’re the reason you bring calm even to my storms, and I wish I could freeze every moment with you.",
  "Day 359 – Every day I discover ordinary days become extraordinary with you, and I wouldn’t trade that for anything.",
  "Day 360 – I adore the way I feel safe when I’m with you, and I’d choose you in every universe.",
  "Day 361 – I adore the way your smile brightens the dullest moments, and it makes me want a thousand more days with you.",
  "Day 362 – I adore the way I feel safe when I’m with you, and it makes me want a thousand more days with you.",
  "Day 363 – Sometimes I think about I find home in your presence, and I’d choose you in every universe.",
  "Day 364 – Every day I discover the smallest glance from you makes my heart race, and that’s why forever feels too short with you.",
  "Day 365 – A full year of love, one note at a time. And still, forever with you wouldn’t be long enough.",
];

